import Level, { Segment } from "./Level";

const LevelOne = new Level([
  new Segment(
    `
      WWWWWWWWWWWWWWWWWWWW,
      WWWWWWWWWWWWWWWWWWWW,
      WWWWWWWWWWWWWWWWWWWW,
      WWWWWWWWWWWWWWWWWWWW,
      WWWWWWWWWWWWWWWWWWWW,
      WWWWWWWWWWWWWWWWWWWW,
      WWWWWWWWWWWWWWWWWWWW,
      WWWWWWWWWWWWWWWWWWWW,
      WWWWWWWWWWWWWWWWWWWW,
      WWWWWWWWWWWWWWWWWWWW,
      WWWWWWWWWWWWWWWWWWWW,
      WWWWWWWWWWWWWWWWWWWW,
    `
  ),
  new Segment(
    `
      XXXXXXXXXXXXXXXXXXXX,
      XXXXXXXXFFFFFFXXXXXX,
      XXXXXXXXFFFFFFXXXXXX,
      XXXXXXXXFFFFFFXXXXXX,
      XXXXXXXXFFFFFFXXXXXX,
      XXXXXXXXFFXXXXXXXXXX,
      XXXXXXXXFFXXXXXXXXXX,
      XXXXXXXXFFXXXXXXXXXX,
      XXXXXFFFFFFFFXXXXXXX,
      XXXXXXXFFFFFFFFXXXXX,
      XXXXXXXFFFFFFFFXXXXX,
      XXXXXXXXXXXXXXXXXXXX,
    `
  ),
]);

export default [LevelOne];